fix directory names of questions

diff --git a/golang/Makefile b/golang/Makefile
--- a/golang/Makefile
+++ b/golang/Makefile
@@ -25,45 +25,62 @@ prepare:
 	@echo "CONTEST=$${contest^^}" > .CONTEST
 	@mkdir -p contests/$${contest^^}
 
+chk:
+	@. .USER && if [ -z "$${USER}" ]; then \
+		echo "XXX Please exec 'make env user=xxxx password=yyyy' first"; \
+		exit 1; \
+	fi
+	@. .CONTEST && if [ -z "$${CONTEST}" ]; then \
+		echo "XXX Please exec 'make prepare contest=yyyy' first"; \
+		exit 1; \
+	fi
+	@. .QUESTION && if [ -z "$${QUESTION}" ]; then \
+		echo "XXX Please exec 'make start q=zzzz' first"; \
+		exit 1; \
+	fi
+
+
 get:
-	rm -rf samples
-	. .USER && . .CONTEST && cd ../tools/ && . venv/bin/activate && python get_samplecases.py -u $${USER} -p $${PASSWORD} -c $${CONTEST} -q $${q} -d ${PWD}/samples
+	@rm -rf samples
+	@make chk
+	@. .USER && . .CONTEST && . .QUESTION && cd ../tools/ && . venv/bin/activate && python get_samplecases.py -u $${USER} -p $${PASSWORD} -c $${CONTEST} -q $${QUESTION} -d ${PWD}/samples
 
 
 start:
 	@if [ -z "${q}" ]; then \
-		echo "***** q is required. Ex. make done q=a"; \
+		echo "***** q is required. Ex. make done q=zzzz"; \
 		exit 1; \
 	fi
-	echo ":::::"
+	@echo "Q=${q}" > .QUESTION
+	@. .CONTEST && echo "QUESTION=$${CONTEST}_${q}" >> .QUESTION
 	@if [ -f main.go ]; then \
 		cp main.go main.tmp.go; \
 	fi
-	echo "222"
 	rm -f go.mod go.sum
 	cp libs/template.go main.go
 	go mod init main
-	make get q=${q}
+	make get
 
 
 done:
-	@if [ -z "${q}" ]; then \
-		echo "***** q is required. Ex. make done q=a"; \
-		exit 1; \
-	fi
-	. .CONTEST && mkdir -p contests/$${CONTEST}/$${q^^} && cp main.go contests/$${CONTEST}/$${q^^}/main.go
-	rm -f go.mod go.sum
+	@make chk
+	. .CONTEST && . .QUESTION && mkdir -p contests/$${CONTEST}/$${QUESTION} && cp main.go contests/$${CONTEST}/$${QUESTION}/main.go
+	rm -f go.mod go.sum .QUESTION
 
 resume:
 	@if [ -z "${q}" ]; then \
-		echo "***** q is required. Ex. make resume q=a"; \
+		echo "***** q is required. Ex. make resume q=zzzz"; \
 		exit 1; \
 	fi
+	@echo "Q=${q}" > .QUESTION
+	@. .CONTEST && echo "QUESTION=$${CONTEST}_${q}" >> .QUESTION
 	@if [ -f main.go ]; then \
 		cp main.go main.tmp.go; \
 	fi
-	. .CONTEST && cp main.go contests/$${CONTEST}/$${q^^}/main.go main.go
+	. .CONTEST && cp main.go contests/$${CONTEST}/$${q}/main.go main.go
 	rm -f go.mod go.sum
+	go mod init main
+	make get
 
 
 run:
@@ -83,20 +100,17 @@ test-contest:
 
 
 test-all:
-	@if [ -z "${q}" ]; then \
-		echo "***** q is required. Ex. make resume q=a"; \
-		exit 1; \
-	fi
-	@. .CONTEST && if [ ! -d "../testcase/$${CONTEST}/${q}" ]; then \
-		echo "***** No test cases for contest $${CONTEST}/${q} are downloaded. Please download them in advance at the following URL."; \
+	@make chk
+	@. .CONTEST && . .QUESTION && if [ ! -d "../testcase/$${CONTEST}/$${Q}" ]; then \
+		echo "***** No test cases for contest $${CONTEST}/${Q} are downloaded. Please download them in advance at the following URL."; \
 		echo "https://www.dropbox.com/sh/nx3tnilzqz7df8a/AAAYlTq2tiEHl5hsESw6-yfLa?dl=0"; \
 		exit 1; \
 	fi
 	@rm -f TEST_RESULT
-	@. .USER && . .CONTEST && for f in ../testcase/$${CONTEST}/${q}/in/*; do \
+	@. .USER && . .CONTEST && . .QUESTION && for f in ../testcase/$${CONTEST}/$${Q}/in/*; do \
 		FILENAME=`basename $${f}`; \
 		echo "--------- TESTING: $${FILENAME} ---------"; \
-		make test case=$${f} answer=../testcase/$${CONTEST}/${q}/out/$${FILENAME} >> TEST_RESULT; \
+		make test case=$${f} answer=../testcase/$${CONTEST}/$${Q}/out/$${FILENAME} >> TEST_RESULT; \
 	done
 	@cat TEST_RESULT
 	@if [ -n "`grep 'code_result: False' TEST_RESULT`" ]; then \
